POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "username": "quocanh",
    "password": "quocanh"
}   

###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
   "username": "quocanh",
    "password": "quocanh"  
}


###
POST http://localhost:3000/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzA0YTJhZTY3NmMyYzc4NmJjZTcwZjgiLCJpYXQiOjE2NjEyNjQ1NzN9.K-53AODhvTtvr0tf0wUY3cMm53YrtLQWQ63-2yr5ChA
    
{
    "title": "React 3",
    "description": "Learned React",
    "url": "React.org",
    "status": "LEARNED"
}

###
GET http://localhost:3000/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzA0YTJhZTY3NmMyYzc4NmJjZTcwZjgiLCJpYXQiOjE2NjEyNjQ1NzN9.K-53AODhvTtvr0tf0wUY3cMm53YrtLQWQ63-2yr5ChA

####

PUT http://localhost:3000/api/posts/62ea5856a3f79f1ebb902cb7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzA0YTJhZTY3NmMyYzc4NmJjZTcwZjgiLCJpYXQiOjE2NjEyNjQ1NzN9.K-53AODhvTtvr0tf0wUY3cMm53YrtLQWQ63-2yr5ChA

{
    "title": "React",
    "description":"React",
    "url": "react.com",
    "status": "Learning"
}

###
DELETE http://localhost:3000/api/posts/62ea5856a3f79f1ebb902cb7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzA0YTJhZTY3NmMyYzc4NmJjZTcwZjgiLCJpYXQiOjE2NjEyNjQ1NzN9.K-53AODhvTtvr0tf0wUY3cMm53YrtLQWQ63-2yr5ChA
