POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "username": "quocanh",
    "password": "quocanh"
}   

###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
   "username": "quocanh",
    "password": "quocanh"  
}


###
POST http://localhost:3000/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmU5ZmUyZDM5NGI2MDlmNWI4ODA0NWUiLCJpYXQiOjE2NjA0NjQ2OTB9.F5vIik1WYZ3AUew0M1XUEEqg9zYyK-2dMJj27gKiPvU
    
{
    "title": "React 3",
    "description": "Learned React",
    "url": "React.org",
    "status": "LEARNED"
}

###
GET http://localhost:3000/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmU5ZmUyZDM5NGI2MDlmNWI4ODA0NWUiLCJpYXQiOjE2NTk1ODc1MDJ9.4saj9M2SQWn5wBKdF44-lp7TnmhpkEaLct8ZcGlYC6I

####

PUT http://localhost:3000/api/posts/62ea5856a3f79f1ebb902cb7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmU5ZmUyZDM5NGI2MDlmNWI4ODA0NWUiLCJpYXQiOjE2NTk1ODc1MDJ9.4saj9M2SQWn5wBKdF44-lp7TnmhpkEaLct8ZcGlYC6I

{
    "title": "React",
    "description":"React",
    "url": "react.com",
    "status": "Learning"
}

###
DELETE http://localhost:3000/api/posts/62ea5856a3f79f1ebb902cb7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmU5ZmUyZDM5NGI2MDlmNWI4ODA0NWUiLCJpYXQiOjE2NTk1ODc1MDJ9.4saj9M2SQWn5wBKdF44-lp7TnmhpkEaLct8ZcGlYC6I
